### ISSUE TITLE
两个该框架上的问题

### ISSUE THREAD

**Issue by littlekan233** [tomato-aoarasi/tomato-chat#1]
# 正题
第一问题：
> 控制台疯狂输出
> ~~全是报错~~

![image](https://github.com/user-attachments/assets/4adb22d9-ddae-42fe-a996-822bcc3c6798)
![image](https://github.com/user-attachments/assets/467069ce-1ffb-4b60-a570-d16d37d473c2)
![image](https://github.com/user-attachments/assets/9a8c9765-6f54-40ad-bddf-71f49342c1b1)
第二问题：
> 大模型跑起来了，但回复...
> __~~《该消息类型暂不支持查看》（手机也不行）~~__

![image](https://github.com/user-attachments/assets/e6e50de5-d314-483f-b6a4-fd6071a5a093)
## 两张其他群u提供的图片：
![2b85b44b0e3962476014058eec140ee2](https://github.com/user-attachments/assets/ff0aad8d-a931-4b66-a137-b48c94b07568)
![44f65160e26d555646294cbea5f9a6c1](https://github.com/user-attachments/assets/568e2f4d-8565-4caf-99a4-7d4ac80d6783)

------------------------
# 环境
Bot使用的协议端：[Lagrange.OneBot](/LagrangeDev/Lagrange.Core)
Python版本：Python 3.11.6 (main, Apr 10 2024, 17:26:07) [GCC 13.2.0] on linux
Commit：4adbb5b

**Comment by 3035936740** [comment]
第二个问题是拉格朗的问题,换成[NapCatQQ](https://github.com/NapNeko/NapCatQQ)

**Comment by 3035936740** [comment]
问题1的话,改改config吧
x86的linux和windows都跑过
没有真的arm环境,要解决自己创建一个分支或者说是发个pr我合并就好了
暂时没有那么多精力处理了
